/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 9536cbbe-e2e6-41ab-a676-f4a6fb85d979
-/

/-
We prove the inequality
(r * (∑ k ∈ Icc 1 n, ↑k * (1 + i)⁻¹ ^ k) + ↑n * (1 + i)⁻¹ ^ n)
/ (r * (∑ k ∈ Icc 1 n, (1 + i)⁻¹ ^ k) + (1 + i)⁻¹ ^ n) < 1 + 1 / i
for n > 1, i > 0, 0 < r < 1, and d > 1.
The proof utilizes geometric series summation formulas and algebraic manipulation.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
(r * (∑ k ∈ Icc 1 n, ↑k * (1 + i)⁻¹ ^ k) + ↑n * (1 + i)⁻¹ ^ n) / (r * (∑ k ∈ Icc 1 n, (1 + i)⁻¹ ^ k) + (1 + i)⁻¹ ^ n) < 1 + 1 / i
-/
theorem inequality_proof (n : ℕ) (hnn : n > 1) (i r : ℝ) (hi : i > 0) (hr : r ≥ i)
:
  (r * (∑ k ∈ Finset.Icc 1 n, (k : ℝ) * (1 + i)⁻¹ ^ k) + (n : ℝ) * (1 + i)⁻¹ ^ n) /
  (r * (∑ k ∈ Finset.Icc 1 n, (1 + i)⁻¹ ^ k) + (1 + i)⁻¹ ^ n) < 1 + 1 / i := by
    rw [ add_div', div_lt_div_iff₀ ] <;> try positivity;
    · -- We'll use the fact that $\sum_{k=1}^n kx^k = x \frac{1 - (n+1)x^n + nx^{n+1}}{(1-x)^2}$.
      have h_sum_formula : ∑ k ∈ Finset.Icc 1 n, (k : ℝ) * (1 + i)⁻¹ ^ k = (1 + i)⁻¹ * (1 - (n + 1) * (1 + i)⁻¹ ^ n + n * (1 + i)⁻¹ ^ (n + 1)) / (1 - (1 + i)⁻¹) ^ 2 := by
        exact eq_div_of_mul_eq ( pow_ne_zero 2 <| by nlinarith [ inv_mul_cancel₀ ( by linarith : ( 1 + i ) ≠ 0 ) ] ) <| Nat.recOn n ( by norm_num ) fun n ihn => by norm_num [ pow_succ, Finset.sum_Ioc_succ_top, (Nat.succ_eq_succ ▸ Finset.Icc_succ_left_eq_Ioc) ] at * ; nlinarith [ inv_mul_cancel₀ ( by linarith : ( 1 + i ) ≠ 0 ) ] ;
      -- We'll use the fact that $\sum_{k=1}^n x^k = \frac{x - x^{n+1}}{1 - x}$.
      have h_sum_formula2 : ∑ k ∈ Finset.Icc 1 n, (1 + i)⁻¹ ^ k = (1 + i)⁻¹ * (1 - (1 + i)⁻¹ ^ n) / (1 - (1 + i)⁻¹) := by
        erw [ geom_sum_Ico ] <;> norm_num [ hi.ne' ];
        -- Combine and simplify the fractions
        field_simp
        ring;
      field_simp [h_sum_formula, h_sum_formula2] at *;
      rw [ h_sum_formula, h_sum_formula2 ] ; ring_nf ; norm_num;
      field_simp at *; ring_nf at *; (
      nlinarith [ show 0 < i ^ 3 by positivity, show 0 < i ^ 2 * n by positivity, show 0 < i * n by positivity, show 0 < i ^ 3 * n by positivity, show 0 < i ^ 2 * n ^ 2 by positivity, show 0 < i * n ^ 2 by positivity, show 0 < i ^ 3 * n ^ 2 by positivity, show ( 1 + i ) ^ n > 1 by exact one_lt_pow₀ ( by linarith ) ( by linarith ) ]);
    · exact add_pos_of_nonneg_of_pos ( mul_nonneg ( by linarith ) ( Finset.sum_nonneg fun _ _ => pow_nonneg ( inv_nonneg.2 ( by linarith ) ) _ ) ) ( pow_pos ( inv_pos.2 ( by linarith ) ) _ )
